version: '3.5'
services:
    clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - "8123:8123"
          - "9000:9000"
          - "9009:9009"
          - "9100:9100"
        ulimits:
          nproc: 65535
          nofile:
            soft: 262144
            hard: 262144

networks:
  default:
    name: clickhouse
    driver: bridge
